### ISSUE TITLE
Is nleap_seconds needed?

### ISSUE THREAD

**Issue by njh** [chmike/posix_tai_time_converter#1]
Hi,

Thanks for making this code available. There is an amazing lack of support for UTC <-> TAI conversion in Operating Systems.

When compiling, I get a warning:
```
cc -Wall -c posix_tai.c
posix_tai.c:13:21: warning: unused variable 'nleap_seconds' [-Wunused-const-variable]
static const size_t nleap_seconds = 28;
                    ^
1 warning generated.
```

I can't see it being used anywhere in your code. Is this variable needed? 

Thanks,

nick.

**Comment by chmike** [comment]
Good point. It’s not needed. Issue fixed.

**Comment by njh** [comment]
Thanks!
