### ISSUE TITLE
The epoch of CLOCK_TAI is 1970-01-01T00:00:00 TAI not UTC

### ISSUE THREAD

**Issue by maxnoe** [chmike/posix_tai_time_converter#3]
From the readme (emphasis mine): 

> TAI time is the time value returned by clock_gettime(CLOCK_TAI,...). It is the number of seconds elapsed since 1970-01-01T00:00:00 **UTC** without leap seconds subtracted.

This is wrong. The epoch of posix time in scale TAI is `1970-01-01T00:00:00 TAI`.

See discussion here for example:

https://github.com/astropy/astropy/issues/11245

**Comment by chmike** [comment]
Good point. According to [wikipedia](https://en.wikipedia.org/wiki/International_Atomic_Time) the TAI clock had a difference of 10 seconds with the UTC clock in 1972. It thus seam that the Jan 1, 1970 epoch for TAI is 8 seconds ahead of the UTC epoch. 

Thank you very much for pointing out this error. I'll fix my code ASAP.

**Comment by maxnoe** [comment]
> It thus seam that the Jan 1, 1970 epoch for TAI is 8 seconds ahead of the UTC epoch.

Even worse, before 1972, there were fractional differences between UTC and TAI. 

The initial offset is 8.000082 seconds (8 seconds + 82 microseconds).

```python
In [1]: from astropy.time import Time

In [2]: t = Time('1970-01-01T00:00:00', scale='utc')

In [3]: t.precision = 6

In [4]: t.tai.iso
Out[4]: '1970-01-01 00:00:08.000082'
```

**Comment by chmike** [comment]
This is indeed a bug. I made a major code update to fix the problem. This bug should not occur anymore since the smallest convertible posix time is Jan 1, 1972.
