### ISSUE TITLE
Wrong results for current times

### ISSUE THREAD

**Issue by maxnoe** [chmike/posix_tai_time_converter#4]
Using this example:

```
#include "stdio.h"
#include "posix_tai.h"


int main() {

	time_t utc[] = {
		0,          // 1970-01-01 00:00:00 UTC
		1483228800, // 2017-01-01 00:00:00 UTC (just after last leap second)
		1500000000, // 2022-05-12 14:00:47 UTC
		1600000000, // 2020-09-13 12:26:40 UTC
		1652364047  // 2022-05-12 14:00:47 UTC
	};
	size_t n = sizeof(utc) / sizeof(time_t);
	for (size_t i=0; i < n; i++) {
		time_t tai = posix2tai(utc[i]);
		printf("%10ld utc to tai: %10ld\n", utc[i], tai);
	}
	return 0;
}
```

I get this result:

```
         0 utc to tai:         10
1483228800 utc to tai: 1483228837
1500000000 utc to tai: 1500000037
1600000000 utc to tai:          0
1652364047 utc to tai:          0
```

First is wrong (dates before 1972 are probably not properly handled) and the two last ones are obviously wrong...

**Comment by chmike** [comment]
OMG ! You have discovered a horrible bug. I'm very sorry. I hope this code was not used to control the trajectory of a rocket.  
I'll fix this now.

**Comment by chmike** [comment]
That's not a bug. It's a feature of the library. The leap second table is unfortunately hard coded because I couldn't find a portable and lightweight function to get the leap second list. 

The table needs to be updated to update the upper date limit. The date you gave is beyond the upper date limit. 

I'm looking for a way to get this leap second table automatically updated, but it would require to use libcurl for instance. This would add an incovenient dependency and a network transaction at each library initialization.

**Comment by chmike** [comment]
Are you considering using this library, because one way to fix it is to erase this repository. 

It is surprising that no valid and definitive engineering solution has been provided so far for this problem.

**Comment by maxnoe** [comment]
@chmike No, I just saw it recommended on stackoverflow.

We are using astropy / erfa. The erfa C library has ways to convert utc to tai: https://github.com/liberfa/erfa/blob/master/src/dtf2d.c

**Comment by chmike** [comment]
I see that they have the same problem. In the file `dat.c` this is what I found. 

``` C
int eraDat(int iy, int im, int id, double fd, double *deltat)
/*
**  - - - - - - -
**   e r a D a t
**  - - - - - - -
**
**  For a given UTC date, calculate Delta(AT) = TAI-UTC.
**
**     :------------------------------------------:
**     :                                          :
**     :                 IMPORTANT                :
**     :                                          :
**     :  A new version of this function must be  :
**     :  produced whenever a new leap second is  :
**     :  announced.  There are four items to     :
**     :  change on each such occasion:           :
**     :                                          :
**     :  1) A new line must be added to the set  :
**     :     of statements that initialize the    :
**     :     array "changes".                     :
**     :                                          :
**     :  2) The constant IYV must be set to the  :
**     :     current year.                        :
**     :                                          :
**     :  3) The "Latest leap second" comment     :
**     :     below must be set to the new leap    :
**     :     second date.                         :
**     :                                          :
**     :  4) The "This revision" comment, later,  :
**     :     must be set to the current date.     :
**     :                                          :
**     :  Change (2) must also be carried out     :
**     :  whenever the function is re-issued,     :
**     :  even if no leap seconds have been       :
**     :  added.                                  :
**     :                                          :
**     :  Latest leap second:  2016 December 31   :
**     :                                          :
**     :__________________________________________:
**
```

They thus also use a hard coded table. This is not better than me and shows that it's a tricky problem to solve. This is not normal today.

**Comment by maxnoe** [comment]
> That's not a bug. It's a feature of the library.

I mean the 0 values! These shouldn't happen. At least for dates until 2022-07-01 you are able to produce valid times, since the IERS already announced that no leap second will be introduced end of June this year

**Comment by chmike** [comment]
The 0 values are obvious error values. The API documentation should be updated to signal that this value is returned when the time values are out of the range with the current code version. erfa should have a same mechanism. 

I'm looking for a better solution. I found one for linux systems. I'm checking if it would work for windows. Is erfa used on Windows too ?

**Comment by maxnoe** [comment]
> . The API documentation should be updated to signal that this value is returned when the time values are out of the range with the current code version.

Ah ok, then it is a question of updating the "validity_date" ?

**Comment by chmike** [comment]
Yes.

I'm updating my library so that it builds the leap second table from the `leap-second.list` file. This will remove the problem of updating the table. I will also clarify the documentation and eventually the API regarding the error case. Do you have a suggestion ? 

On Debian and derived OS, the `leap-second.list` file is provided with the tzdata which is periodically updated as needed. The file is thus there on the operating system just ready to be used. Unfortunately, it is not provided on other unix systems, and of course not on Windows. The user will have to download it himself and ensure it is updated every 6 months with a cron job. I can't see a better simple solution for now. Do you have a better solution ?

**Comment by chmike** [comment]
I pushed a major code update that fixes the reported issues. It is now required to load the leap second files to be able to de the conversion. This avoids the confusion in case the leap second list is outdated.

It would be great if you accept to review and test the new code.

**Comment by chmike** [comment]
I added the function `paconv_init(file_name)` to initialize the list of leap seconds. See the README for a detailed explanation. 
It should now work with all flavor of unix that uses tzdata and store the files in `/usr/share/zoneinfo`. On windows systems, the user will have to provide the file. 

The leap second list is no more hard coded  and the validity range will automatically follow the one of the leap second file. 
Out of valid range posix or tai values yield the special value `paconv_invalid`. This solves the problem raised in this issue.

Thank you very much of your interest in his library and I hope the new API and implementation will match your needs.
